parameter_defaults:
    ControlPlaneDefaultRoute: 192.168.24.1
    ControlPlaneSubnetCidr: '24'
    DnsServers:
    - 10.0.0.1
    EC2MetadataIp: 192.168.24.1
    ExternalAllocationPools:
    -   end: 10.0.0.149
        start: 10.0.0.101
    ExternalInterfaceDefaultRoute: 10.0.0.1
    ExternalNetCidr: 10.0.0.0/24
    ExternalNetworkVlanID: 10
    InternalApiAllocationPools:
    -   end: 172.17.1.149
        start: 172.17.1.10
    InternalApiNetCidr: 172.17.1.0/24
    InternalApiNetworkVlanID: 20
    NeutronBridgeMappings: datacentre:br-ex,tenant:br-isolated
    NeutronExternalNetworkBridge: ''
    NeutronNetworkType: vxlan
    NeutronNetworkVLANRanges: tenant:1000:2000
    NeutronTunnelTypes: vxlan
    StorageAllocationPools:
    -   end: 172.17.3.149
        start: 172.17.3.10
    StorageMgmtAllocationPools:
    -   end: 172.17.4.149
        start: 172.17.4.10
    StorageMgmtNetCidr: 172.17.4.0/24
    StorageMgmtNetworkVlanID: 40
    StorageNetCidr: 172.17.3.0/24
    StorageNetworkVlanID: 30
    TenantAllocationPools:
    -   end: 172.17.2.149
        start: 172.17.2.10
    TenantNetCidr: 172.17.2.0/24
    TenantNetworkVlanID: 50
resource_registry:
    OS::TripleO::BlockStorage::Net::SoftwareConfig: three-nics-vlans/legacy/cinder-storage.yaml
    OS::TripleO::CephStorage::Net::SoftwareConfig: three-nics-vlans/legacy/ceph-storage.yaml
    OS::TripleO::Compute::Net::SoftwareConfig: three-nics-vlans/legacy/compute.yaml
    OS::TripleO::Controller::Net::SoftwareConfig: three-nics-vlans/legacy/controller.yaml
    OS::TripleO::ObjectStorage::Net::SoftwareConfig: three-nics-vlans/legacy/swift-storage.yaml
